### PR TITLE
In-house deployment improvements

### PR DESCRIPTION
**Pull request by selevit**
1. Django setting for disabling registration (set by default when running in docker)
2. Django management command for API token generation:`manage.py generate_api_token` with an optional `--user` parameter
3. Django management command for cleaning up old logs: `manage.py cleanup_old_logs --days=[30]`.
4. Using a random Django secret key by default. Let users pass it as env variable when running docker-compose.
5. Run tests in Github CI instead of travis.
6. Fixed a broken link to vmprof.com.
7. Minor improvements

### CODE REVIEW

**Comment by selevit** [comment]
BTW, [CI passed](https://github.com/selevit/vmprof-server/actions/runs/1899757864) on my local repo.

**Comment by mattip** [comment]
Could you rebase on top of current HEAD? I pushed a commit to add a github action so that actions now run here, but now there is a conflict

**Comment by selevit** [comment]
@mattip sure, done.

**Comment by mattip** [comment]
Cool, the CI runs and even passes. There are some `DeprecationWarnings` about the regex expressions in `cache.py`, not part of this PR. 

@fijal any thoughts? If not I will merge this after the weekend.

**Comment by selevit** [comment]
@mattip any update on this? May we merge this?

**Comment by mattip** [comment]
Thanks @selevit

**Pull request merged**
